name: "CompilationOfManyBreaches.7z"
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "CompilationOfManyBreaches.7z"
  comment: "CompilationOfManyBreaches.7z"
  url: "https://srv-store4.gofile.io/download/Ht5ZSc/CompilationOfManyBreaches.7z?"
  file_name: "CompilationOfManyBreaches.7z"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
