name: "2022_40_Dumps_RU_BE.7z"
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "2022_40_Dumps_RU_BE"
  comment: "2022_40_Dumps_RU_BE"
  url: "https://store2.gofile.io/download/02b9f05a-a00d-4127-84dc-6fa527c924af/Old.7z"
  file_name: "2022_40_Dumps_RU_BE"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent

      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
