name: "fdns_ns"
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "fdns_ns"
  comment: "fdns_ns"
  url: "https://opendata.rapid7.com/sonar.fdns_v2/2021-01-29-1611879127-fdns_ns.json.gz"
  file_name: "Cit0day_Premium"
  piece_size: 22 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
