name: Create torrent using torrenttools
on:
  push:
    paths:
      - ".github/workflows/torrenttools.yml"
      
env:
  name: "CompilationOfManyBreaches"
  comment: "CompilationOfManyBreaches"
  url: "https://srv-store4.gofile.io/download/Ht5ZSc/CompilationOfManyBreaches.7z/?:"
  file_name: "CompilationOfManyBreaches"
  piece_size: auto # auto for automatic calculation, or use the recommended piece size on the README.md file
  protocol_version: 2 # BitTorrent version 1, 2, or hybrid
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install torrenttools
        run: |
          sudo add-apt-repository ppa:fbdtemme/torrenttools
          sudo apt-get update
          sudo apt-get install torrenttools
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using torrenttools
        run: torrenttools create -v $protocol_version -o "${name}.torrent" -w "$url" -c "$comment" -l $piece_size "$file_name" # Tested on v0.1.3
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
